from django.utils.text import slugify


SITE_LANGUAGE_SESSION_KEY = "medical_app_site_language"
DEFAULT_SITE_LANGUAGE = "english"

LANGUAGE_METADATA = {
    "english": {
        "label": "English",
        "locale": "en",
        "direction": "ltr",
        "speech_code": "en",
    },
    "hindi": {
        "label": "Hindi",
        "locale": "hi",
        "direction": "ltr",
        "speech_code": "hi",
    },
    "urdu": {
        "label": "Urdu",
        "locale": "ur",
        "direction": "rtl",
        "speech_code": "ur",
    },
    "arabic": {
        "label": "Arabic",
        "locale": "ar",
        "direction": "rtl",
        "speech_code": "ar",
    },
    "bengali": {
        "label": "Bengali",
        "locale": "bn",
        "direction": "ltr",
        "speech_code": "bn",
    },
}

SITE_UI_TRANSLATIONS = {
    "hindi": {
        "AI Medical Assistant": "एआई मेडिकल असिस्टेंट",
        "Clinical decision-support workspace": "क्लिनिकल निर्णय-सहायता कार्यक्षेत्र",
        "Home": "होम",
        "Chat": "चैट",
        "Sign In": "साइन इन",
        "Signed in": "साइन इन किया गया",
        "Navigation": "नेविगेशन",
        "Dashboard": "डैशबोर्ड",
        "History": "इतिहास",
        "Profile Settings": "प्रोफ़ाइल सेटिंग्स",
        "Preferences": "पसंदें",
        "Register": "रजिस्टर",
        "Logout": "लॉगआउट",
        "Theme": "थीम",
        "Light": "लाइट",
        "Dark": "डार्क",
        "Website Language": "वेबसाइट भाषा",
        "Language": "भाषा",
        "English": "अंग्रेज़ी",
        "Hindi": "हिंदी",
        "Urdu": "उर्दू",
        "Arabic": "अरबी",
        "Bengali": "बांग्ला",
        "Skip to content": "सामग्री पर जाएँ",
        "Important Notice": "महत्वपूर्ण सूचना",
        "Access": "एक्सेस",
        "Built for a professional healthcare workflow.": "प्रोफेशनल हेल्थकेयर वर्कफ़्लो के लिए बनाया गया।",
        "Clinical Intake": "क्लिनिकल इनटेक",
        "Capture symptoms, analyze reports and images, and generate clinical decision support.": "लक्षण कैप्चर करें, रिपोर्ट और इमेज का विश्लेषण करें, और क्लिनिकल निर्णय सहायता प्राप्त करें।",
        "Record a voice note, upload a medical image, attach report findings, or type symptoms manually. The assistant returns a structured response, saves the clinical record, and supports follow-up analytics on the dashboard.": "वॉइस नोट रिकॉर्ड करें, मेडिकल इमेज अपलोड करें, रिपोर्ट फ़ाइंडिंग्स जोड़ें या लक्षण मैन्युअली लिखें। असिस्टेंट संरचित उत्तर देता है, क्लिनिकल रिकॉर्ड सेव करता है और डैशबोर्ड पर फॉलो-अप एनालिटिक्स में मदद करता है।",
        "Voice Recording": "वॉइस रिकॉर्डिंग",
        "Capture the patient narrative directly from the browser.": "ब्राउज़र से सीधे मरीज की जानकारी रिकॉर्ड करें।",
        "Start Recording": "रिकॉर्डिंग शुरू करें",
        "Stop Recording": "रिकॉर्डिंग रोकें",
        "The recorded file will be attached to this form automatically.": "रिकॉर्ड की गई फ़ाइल इस फ़ॉर्म में अपने आप जुड़ जाएगी।",
        "Transcription": "ट्रांसक्रिप्शन",
        "Speech-to-text output appears here after processing.": "प्रोसेसिंग के बाद स्पीच-टू-टेक्स्ट आउटपुट यहाँ दिखाई देगा।",
        "Transcribed speech will appear here.": "ट्रांसक्राइब किया गया भाषण यहाँ दिखाई देगा।",
        "Medical Image": "मेडिकल इमेज",
        "Upload an image file or capture one from the camera.": "इमेज फ़ाइल अपलोड करें या कैमरे से कैप्चर करें।",
        "Open Camera": "कैमरा खोलें",
        "Capture Photo": "फ़ोटो कैप्चर करें",
        "Doctor Response": "डॉक्टर रिस्पॉन्स",
        "Structured guidance is shown here once analysis completes.": "विश्लेषण पूरा होने पर संरचित मार्गदर्शन यहाँ दिखेगा।",
        "The AI summary will appear here.": "एआई सारांश यहाँ दिखाई देगा।",
        "Report Findings Summary": "रिपोर्ट फ़ाइंडिंग्स सारांश",
        "Structured explanation of uploaded report data and detected clinical patterns.": "अपलोड की गई रिपोर्ट डेटा और पहचाने गए क्लिनिकल पैटर्न का संरचित विवरण।",
        "Report analysis findings will appear here.": "रिपोर्ट विश्लेषण की जानकारी यहाँ दिखाई देगी।",
        "Symptoms": "लक्षण",
        "Use this when you want to describe the case manually.": "जब आप केस को मैन्युअली बताना चाहते हैं तब इसका उपयोग करें।",
        "Describe the symptoms, duration, severity, and any relevant history.": "लक्षण, उनकी अवधि, गंभीरता और संबंधित इतिहास लिखें।",
        "Voice Output": "वॉइस आउटपुट",
        "Listen to the generated spoken summary when available.": "उपलब्ध होने पर जनरेट किया गया बोला गया सारांश सुनें।",
        "Voice summary is disabled in your profile preferences.": "आपकी प्रोफ़ाइल पसंदों में वॉइस सारांश बंद है।",
        "Audio playback becomes available after a successful analysis.": "सफल विश्लेषण के बाद ऑडियो प्लेबैक उपलब्ध होगा।",
        "Analyze Patient": "मरीज का विश्लेषण करें",
        "Reports Workspace": "रिपोर्ट्स वर्कस्पेस",
        "Need report interpretation or previous-vs-current comparison?": "रिपोर्ट की व्याख्या या पुरानी बनाम नई तुलना चाहिए?",
        "Open the dedicated reports page for current medical report review and previous report comparison.": "वर्तमान मेडिकल रिपोर्ट समीक्षा और पिछली रिपोर्ट तुलना के लिए समर्पित रिपोर्ट पेज खोलें।",
        "Open Reports & Comparison": "रिपोर्ट्स और तुलना खोलें",
        "Latest Clinical Record Saved": "नवीनतम क्लिनिकल रिकॉर्ड सेव हो गया",
        "This analysis has been stored for comparison, dashboard analytics, and treatment tracking.": "यह विश्लेषण तुलना, डैशबोर्ड एनालिटिक्स और ट्रीटमेंट ट्रैकिंग के लिए सेव किया गया है।",
        "Open Record": "रिकॉर्ड खोलें",
        "Predicted Condition": "अनुमानित स्थिति",
        "Risk Level": "जोखिम स्तर",
        "Detected Conditions": "पहचानी गई स्थितियाँ",
        "Model Source": "मॉडल स्रोत",
        "Disease Level": "रोग स्तर",
        "Not identified": "पहचाना नहीं गया",
        "Disease Burden Comparison": "रोग भार तुलना",
        "Previous and current reports were compared automatically to show improvement and remaining disease burden.": "पिछली और वर्तमान रिपोर्टों की स्वचालित तुलना करके सुधार और बचा हुआ रोग भार दिखाया गया।",
        "Current level": "वर्तमान स्तर",
        "Remaining": "शेष",
        "Previous Report": "पिछली रिपोर्ट",
        "Current Report": "वर्तमान रिपोर्ट",
        "Interpretation": "व्याख्या",
        "Reports & Comparison": "रिपोर्ट्स और तुलना",
        "Analyze current reports and compare previous records from one focused page.": "एक केंद्रित पेज से वर्तमान रिपोर्टों का विश्लेषण करें और पिछली रिकॉर्ड्स की तुलना करें।",
        "Upload or paste the latest report, add an earlier report when needed, and generate a structured report interpretation with comparison insights.": "नवीनतम रिपोर्ट अपलोड या पेस्ट करें, ज़रूरत हो तो पुरानी रिपोर्ट जोड़ें और तुलना की जानकारी के साथ संरचित रिपोर्ट व्याख्या प्राप्त करें।",
        "Back to Clinical Intake": "क्लिनिकल इनटेक पर वापस जाएँ",
        "Analyze Reports": "रिपोर्ट्स का विश्लेषण करें",
        "Patient Chat": "मरीज चैट",
        "Follow-up Chat": "फॉलो-अप चैट",
        "Continue the clinical conversation with a more focused workspace.": "एक अधिक केंद्रित वर्कस्पेस के साथ क्लिनिकल बातचीत जारी रखें।",
        "Ask follow-up questions, clarify symptoms, and keep supporting attachments together with the patient discussion.": "फॉलो-अप प्रश्न पूछें, लक्षण स्पष्ट करें, और सहायक अटैचमेंट्स को मरीज चर्चा के साथ रखें।",
        "Open History": "इतिहास खोलें",
        "Conversation": "बातचीत",
        "Review prior responses and continue the clinical thread with clear follow-up context.": "पुराने उत्तर देखें और स्पष्ट फॉलो-अप संदर्भ के साथ क्लिनिकल बातचीत जारी रखें।",
        "AI Assisted": "एआई सहायता प्राप्त",
        "Attachment Ready": "अटैचमेंट तैयार",
        "Open attachment": "अटैचमेंट खोलें",
        "No conversation yet": "अभी तक कोई बातचीत नहीं",
        "Start with symptoms, medications, report findings, or the next question you want the assistant to help organize.": "लक्षण, दवाइयाँ, रिपोर्ट फ़ाइंडिंग्स या अगले प्रश्न से शुरुआत करें जिसे आप असिस्टेंट से व्यवस्थित करवाना चाहते हैं।",
        "Send a Message": "संदेश भेजें",
        "Share a follow-up question or upload a supporting image or PDF for context.": "फॉलो-अप प्रश्न भेजें या संदर्भ के लिए इमेज या PDF अपलोड करें।",
        "Clinical Message": "क्लिनिकल संदेश",
        "Attachment": "अटैचमेंट",
        "Accepted formats: JPG, JPEG, PNG, or PDF up to 5 MB.": "स्वीकृत फ़ॉर्मैट: JPG, JPEG, PNG या PDF, अधिकतम 5 MB।",
        "Keep messages concise and include duration, severity, and any recent changes when relevant.": "संदेश संक्षिप्त रखें और जहाँ ज़रूरी हो अवधि, गंभीरता और हाल के बदलाव शामिल करें।",
        "Send Message": "संदेश भेजें",
        "Workspace Summary": "वर्कस्पेस सारांश",
        "A quick snapshot of the current follow-up session.": "वर्तमान फॉलो-अप सत्र का त्वरित सारांश।",
        "Messages": "संदेश",
        "Attachments": "अटैचमेंट्स",
        "Best Practices": "सर्वोत्तम तरीके",
        "Use the chat more effectively with structured clinical follow-up.": "संरचित क्लिनिकल फॉलो-अप के साथ चैट का अधिक प्रभावी उपयोग करें।",
        "Quick Actions": "क्विक एक्शन्स",
        "Navigate to adjacent clinical workflows.": "संबंधित क्लिनिकल वर्कफ़्लो पर जाएँ।",
        "Go to Clinical Intake": "क्लिनिकल इनटेक पर जाएँ",
        "Review Conversation History": "बातचीत का इतिहास देखें",
        "Sign in to your account": "अपने खाते में साइन इन करें",
        "Secure clinician access": "सुरक्षित क्लिनिशियन एक्सेस",
        "Welcome Back": "वापसी पर स्वागत है",
        "Access the dashboard, saved conversations, user activity, and account settings.": "डैशबोर्ड, सेव की गई बातचीत, यूज़र गतिविधि और अकाउंट सेटिंग्स एक्सेस करें।",
        "Login with Gmail": "Gmail से लॉगिन करें",
        "Google opens its account chooser directly. If you're already signed in to Google, you can continue with one click.": "Google सीधे अकाउंट चुनने का विकल्प खोलता है। यदि आप पहले से Google में साइन इन हैं, तो एक क्लिक में आगे बढ़ सकते हैं।",
        "or continue with password": "या पासवर्ड से जारी रखें",
        "Email ID / User ID": "ईमेल आईडी / यूज़र आईडी",
        "Password": "पासवर्ड",
        "Need an account?": "क्या अकाउंट चाहिए?",
        "Create one": "एक बनाएँ",
        "Demo admin credentials: Admin / Admin123": "डेमो एडमिन क्रेडेंशियल्स: Admin / Admin123",
        "Profile & Preferences": "प्रोफ़ाइल और पसंदें",
        "Profile Settings": "प्रोफ़ाइल सेटिंग्स",
        "Personalize the assistant while keeping your medical profile and security settings current.": "अपने मेडिकल प्रोफ़ाइल और सुरक्षा सेटिंग्स को अद्यतन रखते हुए असिस्टेंट को व्यक्तिगत बनाएँ।",
        "Preferences Summary": "पसंदों का सारांश",
        "Website output language": "वेबसाइट आउटपुट भाषा",
        "Response Style": "रिस्पॉन्स स्टाइल",
        "AI Behavior": "एआई व्यवहार",
        "Privacy": "प्राइवेसी",
        "Performance": "परफॉर्मेंस",
        "Voice Summary": "वॉइस सारांश",
        "Enabled": "सक्रिय",
        "Disabled": "निष्क्रिय",
        "Profile, Medical Info & AI Preferences": "प्रोफ़ाइल, मेडिकल जानकारी और एआई पसंदें",
        "Personal Info": "व्यक्तिगत जानकारी",
        "Medical Info": "मेडिकल जानकारी",
        "Update Profile": "प्रोफ़ाइल अपडेट करें",
        "Update Password": "पासवर्ड अपडेट करें",
        "Back to Dashboard": "डैशबोर्ड पर वापस जाएँ",
        "Saved analyses": "सेव किए गए विश्लेषण",
        "Compared reports": "तुलना की गई रिपोर्ट्स",
        "High-risk cases": "उच्च-जोखिम केस",
        "Active devices": "सक्रिय डिवाइस",
        "Dashboard": "डैशबोर्ड",
        "Analytics": "एनालिटिक्स",
        "History Timeline": "इतिहास टाइमलाइन",
        "Filter + Search": "फ़िल्टर + खोज",
        "Timeline": "टाइमलाइन",
        "Detailed View": "विस्तृत दृश्य",
        "View Record": "रिकॉर्ड देखें",
        "Compare": "तुलना करें",
        "No session selected": "कोई सत्र चयनित नहीं है",
        "You have been signed out.": "आप साइन आउट हो गए हैं।",
        "Welcome back. Your dashboard is ready.": "वापसी पर स्वागत है। आपका डैशबोर्ड तैयार है।",
        "Profile details updated successfully.": "प्रोफ़ाइल विवरण सफलतापूर्वक अपडेट हो गया।",
        "Password updated successfully.": "पासवर्ड सफलतापूर्वक अपडेट हो गया।",
        "User details updated successfully.": "यूज़र विवरण सफलतापूर्वक अपडेट हो गया।",
        "User deleted successfully.": "यूज़र सफलतापूर्वक हटाया गया।",
        "Treatment entry deleted successfully.": "ट्रीटमेंट एंट्री सफलतापूर्वक हटाई गई।",
        "The assistant could not generate a response right now.": "असिस्टेंट अभी उत्तर जनरेट नहीं कर सका।",
        "Enter a valid email/user ID and password.": "मान्य ईमेल/यूज़र आईडी और पासवर्ड दर्ज करें।",
        "This account is inactive.": "यह खाता निष्क्रिय है।",
        "Enter a valid email ID.": "मान्य ईमेल आईडी दर्ज करें।",
        "Enter a valid mobile number with 10 to 15 digits.": "10 से 15 अंकों वाला मान्य मोबाइल नंबर दर्ज करें।",
        "Enter a valid 6-digit email OTP.": "मान्य 6-अंकों का ईमेल OTP दर्ज करें।",
        "Enter a valid 6-digit mobile OTP.": "मान्य 6-अंकों का मोबाइल OTP दर्ज करें।",
        "Only JPG, JPEG, PNG, and PDF files are allowed.": "सिर्फ JPG, JPEG, PNG और PDF फ़ाइलें स्वीकार हैं।",
        "File size must be under 5 MB.": "फ़ाइल साइज़ 5 MB से कम होना चाहिए।",
        "Low": "कम",
        "Medium": "मध्यम",
        "High": "उच्च",
        "Balanced": "संतुलित",
        "Concise": "संक्षिप्त",
        "Detailed": "विस्तृत",
        "Reassuring": "आश्वस्त करने वाला",
        "Clinical": "क्लिनिकल",
        "Conservative": "सावधानीपूर्ण",
        "Proactive alerts": "प्रोएक्टिव अलर्ट्स",
        "Important only": "केवल महत्वपूर्ण",
        "Analysis updates": "विश्लेषण अपडेट्स",
        "Full digest": "पूर्ण डाइजेस्ट",
        "Standard": "मानक",
        "Private": "निजी",
        "Strict": "सख्त",
        "Fast": "तेज़",
        "High quality": "उच्च गुणवत्ता",
    },
    "urdu": {
        "AI Medical Assistant": "اے آئی میڈیکل اسسٹنٹ",
        "Clinical decision-support workspace": "کلینیکل فیصلہ معاون ورک اسپیس",
        "Home": "ہوم",
        "Chat": "چیٹ",
        "Sign In": "سائن اِن",
        "Signed in": "سائن اِن شدہ",
        "Dashboard": "ڈیش بورڈ",
        "History": "ہسٹری",
        "Profile Settings": "پروفائل سیٹنگز",
        "Preferences": "ترجیحات",
        "Register": "رجسٹر",
        "Logout": "لاگ آؤٹ",
        "Theme": "تھیم",
        "Light": "لائٹ",
        "Dark": "ڈارک",
        "Website Language": "ویب سائٹ زبان",
        "Language": "زبان",
        "English": "انگریزی",
        "Hindi": "ہندی",
        "Urdu": "اردو",
        "Arabic": "عربی",
        "Bengali": "بنگالی",
        "Clinical Intake": "کلینیکل اِن ٹیک",
        "Analyze Patient": "مریض کا تجزیہ کریں",
        "Reports & Comparison": "رپورٹس اور موازنہ",
        "Login with Gmail": "Gmail سے لاگ اِن کریں",
        "Sign in to your account": "اپنے اکاؤنٹ میں سائن اِن کریں",
        "Welcome Back": "خوش آمدید",
        "Password": "پاس ورڈ",
        "Email ID / User ID": "ای میل آئی ڈی / یوزر آئی ڈی",
        "Dashboard": "ڈیش بورڈ",
        "History Timeline": "ہسٹری ٹائم لائن",
        "Follow-up Chat": "فالو اپ چیٹ",
        "Profile & Preferences": "پروفائل اور ترجیحات",
        "Language": "زبان",
        "Response Style": "جواب کا انداز",
        "AI Behavior": "اے آئی رویہ",
        "Privacy": "پرائیویسی",
        "Performance": "کارکردگی",
        "Voice Summary": "آواز میں خلاصہ",
        "Enabled": "فعال",
        "Disabled": "غیر فعال",
        "Update Profile": "پروفائل اپڈیٹ کریں",
        "Update Password": "پاس ورڈ اپڈیٹ کریں",
        "Back to Dashboard": "ڈیش بورڈ پر واپس جائیں",
        "Low": "کم",
        "Medium": "درمیانہ",
        "High": "زیادہ",
        "Balanced": "متوازن",
        "Fast": "تیز",
        "Standard": "معیاری",
    },
    "arabic": {
        "AI Medical Assistant": "المساعد الطبي بالذكاء الاصطناعي",
        "Clinical decision-support workspace": "مساحة عمل لدعم القرار السريري",
        "Home": "الرئيسية",
        "Chat": "الدردشة",
        "Sign In": "تسجيل الدخول",
        "Signed in": "تم تسجيل الدخول",
        "Dashboard": "لوحة التحكم",
        "History": "السجل",
        "Profile Settings": "إعدادات الملف الشخصي",
        "Preferences": "التفضيلات",
        "Register": "إنشاء حساب",
        "Logout": "تسجيل الخروج",
        "Theme": "المظهر",
        "Light": "فاتح",
        "Dark": "داكن",
        "Website Language": "لغة الموقع",
        "Language": "اللغة",
        "English": "الإنجليزية",
        "Hindi": "الهندية",
        "Urdu": "الأردية",
        "Arabic": "العربية",
        "Bengali": "البنغالية",
        "Clinical Intake": "الإدخال السريري",
        "Analyze Patient": "تحليل المريض",
        "Reports & Comparison": "التقارير والمقارنة",
        "Login with Gmail": "تسجيل الدخول عبر Gmail",
        "Sign in to your account": "سجّل الدخول إلى حسابك",
        "Welcome Back": "مرحبًا بعودتك",
        "Password": "كلمة المرور",
        "Email ID / User ID": "البريد الإلكتروني / اسم المستخدم",
        "History Timeline": "الخط الزمني للسجل",
        "Follow-up Chat": "دردشة المتابعة",
        "Profile & Preferences": "الملف الشخصي والتفضيلات",
        "Response Style": "أسلوب الرد",
        "AI Behavior": "سلوك الذكاء الاصطناعي",
        "Privacy": "الخصوصية",
        "Performance": "الأداء",
        "Voice Summary": "الملخص الصوتي",
        "Enabled": "مفعّل",
        "Disabled": "معطّل",
        "Update Profile": "تحديث الملف الشخصي",
        "Update Password": "تحديث كلمة المرور",
        "Back to Dashboard": "العودة إلى لوحة التحكم",
        "Low": "منخفض",
        "Medium": "متوسط",
        "High": "مرتفع",
        "Balanced": "متوازن",
        "Fast": "سريع",
        "Standard": "قياسي",
    },
    "bengali": {
        "AI Medical Assistant": "এআই মেডিক্যাল অ্যাসিস্ট্যান্ট",
        "Clinical decision-support workspace": "ক্লিনিক্যাল সিদ্ধান্ত সহায়তা ওয়ার্কস্পেস",
        "Home": "হোম",
        "Chat": "চ্যাট",
        "Sign In": "সাইন ইন",
        "Signed in": "সাইন ইন করা হয়েছে",
        "Dashboard": "ড্যাশবোর্ড",
        "History": "ইতিহাস",
        "Profile Settings": "প্রোফাইল সেটিংস",
        "Preferences": "পছন্দসমূহ",
        "Register": "রেজিস্টার",
        "Logout": "লগআউট",
        "Theme": "থিম",
        "Light": "লাইট",
        "Dark": "ডার্ক",
        "Website Language": "ওয়েবসাইট ভাষা",
        "Language": "ভাষা",
        "English": "ইংরেজি",
        "Hindi": "হিন্দি",
        "Urdu": "উর্দু",
        "Arabic": "আরবি",
        "Bengali": "বাংলা",
        "Clinical Intake": "ক্লিনিক্যাল ইনটেক",
        "Analyze Patient": "রোগী বিশ্লেষণ করুন",
        "Reports & Comparison": "রিপোর্ট ও তুলনা",
        "Login with Gmail": "Gmail দিয়ে লগইন করুন",
        "Sign in to your account": "আপনার অ্যাকাউন্টে সাইন ইন করুন",
        "Welcome Back": "ফিরে আসায় স্বাগতম",
        "Password": "পাসওয়ার্ড",
        "Email ID / User ID": "ইমেইল আইডি / ইউজার আইডি",
        "History Timeline": "ইতিহাস টাইমলাইন",
        "Follow-up Chat": "ফলো-আপ চ্যাট",
        "Profile & Preferences": "প্রোফাইল ও পছন্দসমূহ",
        "Response Style": "উত্তরের ধরন",
        "AI Behavior": "এআই আচরণ",
        "Privacy": "গোপনীয়তা",
        "Performance": "পারফরম্যান্স",
        "Voice Summary": "ভয়েস সারাংশ",
        "Enabled": "সক্রিয়",
        "Disabled": "নিষ্ক্রিয়",
        "Update Profile": "প্রোফাইল আপডেট করুন",
        "Update Password": "পাসওয়ার্ড আপডেট করুন",
        "Back to Dashboard": "ড্যাশবোর্ডে ফিরে যান",
        "Low": "কম",
        "Medium": "মাঝারি",
        "High": "উচ্চ",
        "Balanced": "সামঞ্জস্যপূর্ণ",
        "Fast": "দ্রুত",
        "Standard": "স্ট্যান্ডার্ড",
    },
}


def normalize_language(value):
    normalized = slugify(str(value or "").strip()).replace("-", "_")
    normalized = normalized.replace("_", "")
    for key in LANGUAGE_METADATA:
        if normalized == key.replace("_", ""):
            return key
    return DEFAULT_SITE_LANGUAGE


def get_language_choices():
    return [(code, metadata["label"]) for code, metadata in LANGUAGE_METADATA.items()]


def get_language_label(language):
    return LANGUAGE_METADATA.get(normalize_language(language), LANGUAGE_METADATA[DEFAULT_SITE_LANGUAGE])["label"]


def get_language_locale(language):
    return LANGUAGE_METADATA.get(normalize_language(language), LANGUAGE_METADATA[DEFAULT_SITE_LANGUAGE])["locale"]


def get_text_direction(language):
    return LANGUAGE_METADATA.get(normalize_language(language), LANGUAGE_METADATA[DEFAULT_SITE_LANGUAGE])["direction"]


def get_speech_language_code(language):
    return LANGUAGE_METADATA.get(normalize_language(language), LANGUAGE_METADATA[DEFAULT_SITE_LANGUAGE])[
        "speech_code"
    ]


def get_request_language(request, *, user_profile=None, explicit_language=None):
    if explicit_language:
        return normalize_language(explicit_language)

    request_language = getattr(request, "site_language", "")
    if request_language:
        return normalize_language(request_language)

    session = getattr(request, "session", None)
    if session:
        session_language = session.get(SITE_LANGUAGE_SESSION_KEY)
        if session_language:
            return normalize_language(session_language)

    if user_profile and getattr(user_profile, "language_preference", ""):
        return normalize_language(user_profile.language_preference)

    return DEFAULT_SITE_LANGUAGE


def build_translation_catalog(language):
    normalized_language = normalize_language(language)
    if normalized_language == DEFAULT_SITE_LANGUAGE:
        return {}
    return SITE_UI_TRANSLATIONS.get(normalized_language, {})


def translate_text(text, language):
    if not text:
        return text
    normalized_language = normalize_language(language)
    if normalized_language == DEFAULT_SITE_LANGUAGE:
        return text
    return SITE_UI_TRANSLATIONS.get(normalized_language, {}).get(str(text), text)
