# Generated by Django 6.0.3 on 2026-03-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_demo_data(apps, schema_editor):
    FeaturedImage = apps.get_model("medical_app", "FeaturedImage")

    if not FeaturedImage.objects.exists():
        FeaturedImage.objects.bulk_create(
            [
                FeaturedImage(
                    title="Dashboard Overview",
                    caption="Open the analytics dashboard to review active sessions, user activity, and engagement trends.",
                    image_url="https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80",
                    target_url="/dashboard/",
                    display_order=1,
                    is_active=True,
                ),
                FeaturedImage(
                    title="Clinical Follow-Up Chat",
                    caption="Continue patient conversations, ask follow-up questions, and keep attachments with the case history.",
                    image_url="https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
                    target_url="/chat/",
                    display_order=2,
                    is_active=True,
                ),
                FeaturedImage(
                    title="Patient History",
                    caption="Review previously saved sessions, responses, and supporting files from a single timeline view.",
                    image_url="https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80",
                    target_url="/history/",
                    display_order=3,
                    is_active=True,
                ),
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('caption', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('target_url', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('last_known_location', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen',),
                'unique_together': {('user', 'session_key')},
            },
        ),
        migrations.RunPython(seed_demo_data, migrations.RunPython.noop),
    ]
