# Generated by Django 6.0.3 on 2026-03-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_featuredimage_userprofile_loginactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('symptoms_text', models.TextField(blank=True)),
                ('transcription_text', models.TextField(blank=True)),
                ('report_text', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('medical_image', models.FileField(blank=True, null=True, upload_to='analysis_images/')),
                ('ai_summary', models.TextField(blank=True)),
                ('predicted_condition', models.CharField(blank=True, max_length=120)),
                ('detected_conditions_count', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=32)),
                ('confidence_score', models.FloatField(default=0)),
                ('progression_status', models.CharField(blank=True, max_length=40)),
                ('model_source', models.CharField(default='heuristic', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TreatmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('doctor_id', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=150)),
                ('contact_details', models.CharField(blank=True, max_length=150)),
                ('treatment_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_entries', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical_app.medicalanalysis')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
