# Generated by Django 6.0.3 on 2026-03-19 11:38

import django.db.models.deletion
from django.db import migrations, models


GENERIC_CONDITION_LABEL = "General review required"
GENERIC_CONDITION_LABELS = {
    GENERIC_CONDITION_LABEL.lower(),
    "visual review suggested",
    "image model prediction",
}


def _is_generic_condition_label(value):
    return not value or value.strip().lower() in GENERIC_CONDITION_LABELS


def _build_input_text(analysis):
    parts = []

    if analysis.symptoms_text:
        parts.append(f"Symptoms: {analysis.symptoms_text.strip()}")
    if analysis.transcription_text:
        parts.append(f"Voice transcription: {analysis.transcription_text.strip()}")
    if analysis.report_text:
        parts.append(f"Report content: {analysis.report_text.strip()}")

    return "\n\n".join(part for part in parts if part).strip()


def _resolve_target_condition(analysis, treatment):
    predicted_condition = (analysis.predicted_condition or "").strip()
    if not _is_generic_condition_label(predicted_condition):
        return predicted_condition

    specialization = (treatment.specialization or "").strip()
    if specialization:
        return specialization

    return GENERIC_CONDITION_LABEL


def _calculate_quality_score(analysis, treatment, input_text):
    score = 0

    if input_text:
        score += 35
    if analysis.symptoms_text:
        score += 10
    if analysis.transcription_text:
        score += 10
    if analysis.report_text:
        score += 15
    if analysis.ai_summary:
        score += 10
    if not _is_generic_condition_label(analysis.predicted_condition):
        score += 5
    if treatment.specialization:
        score += 5
    if len((treatment.treatment_notes or "").split()) >= 8:
        score += 10

    return min(score, 100)


def backfill_training_records(apps, schema_editor):
    TreatmentEntry = apps.get_model("medical_app", "TreatmentEntry")
    TreatmentTrainingRecord = apps.get_model("medical_app", "TreatmentTrainingRecord")

    for treatment in TreatmentEntry.objects.select_related("analysis", "added_by").all():
        analysis = treatment.analysis
        input_text = _build_input_text(analysis)

        TreatmentTrainingRecord.objects.update_or_create(
            treatment=treatment,
            defaults={
                "analysis": analysis,
                "source_type": "doctor_reviewed_case",
                "input_text": input_text,
                "ai_context": (analysis.ai_summary or "").strip(),
                "target_condition": _resolve_target_condition(analysis, treatment),
                "target_specialization": (treatment.specialization or "").strip(),
                "target_treatment": (treatment.treatment_notes or "").strip(),
                "feature_snapshot": {
                    "analysis_id": analysis.id,
                    "analysis_title": analysis.title,
                    "risk_level": analysis.risk_level,
                    "confidence_score": analysis.confidence_score,
                    "detected_conditions_count": analysis.detected_conditions_count,
                    "progression_status": analysis.progression_status,
                    "model_source": analysis.model_source,
                    "doctor_name": treatment.doctor_name,
                    "doctor_id": treatment.doctor_id,
                    "contact_details": treatment.contact_details,
                    "added_by": treatment.added_by.username if treatment.added_by else "",
                },
                "quality_score": _calculate_quality_score(analysis, treatment, input_text),
                "is_approved": bool((treatment.treatment_notes or "").strip()),
                "review_notes": "",
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='doctor_reviewed_case', max_length=40)),
                ('input_text', models.TextField()),
                ('ai_context', models.TextField(blank=True)),
                ('target_condition', models.CharField(blank=True, max_length=120)),
                ('target_specialization', models.CharField(blank=True, max_length=150)),
                ('target_treatment', models.TextField()),
                ('feature_snapshot', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('review_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='medical_app.medicalanalysis')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_record', to='medical_app.treatmententry')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RunPython(backfill_training_records, noop_reverse),
    ]
