# Generated by Django 6.0.3 on 2026-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0005_treatmenttrainingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalanalysis',
            name='disease_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='percentage_reduced',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='percentage_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='previous_disease_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='previous_report_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='previous_report_text',
            field=models.TextField(blank=True),
        ),
    ]
