# Generated by Django 6.0.3 on 2026-03-25 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_medicalanalysis_disease_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'is_active', '-last_seen'], name='login_user_active_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalanalysis',
            index=models.Index(fields=['user', '-created_at'], name='analysis_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmenttrainingrecord',
            index=models.Index(fields=['source_type', 'is_approved', '-updated_at'], name='training_source_approved_idx'),
        ),
    ]
