# Generated by Django 6.0.3 on 2026-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0007_chatmessage_chat_session_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_risk_preference',
            field=models.CharField(default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_compare_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(default='important_only', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='performance_mode',
            field=models.CharField(default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_mode',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_style',
            field=models.CharField(default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voice_summary_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
