# Generated by Django 6.0.3 on 2026-03-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0008_userprofile_ai_risk_preference_userprofile_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_key', models.CharField(default='default', editable=False, max_length=40, unique=True)),
                ('chat_model_name', models.CharField(default='meta-llama/llama-4-scout-17b-16e-instruct', max_length=150)),
                ('analysis_model_name', models.CharField(default='meta-llama/llama-4-scout-17b-16e-instruct', max_length=150)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.2)),
                ('top_p', models.FloatField(default=0.9)),
                ('max_output_tokens', models.PositiveIntegerField(default=900)),
                ('qa_min_confidence', models.FloatField(default=0.2)),
                ('classifier_min_class_occurrences', models.PositiveSmallIntegerField(default=3)),
                ('classifier_train_ratio', models.FloatField(default=0.8)),
                ('qa_train_ratio', models.FloatField(default=0.8)),
                ('random_seed', models.PositiveIntegerField(default=42)),
                ('auto_retrain_enabled', models.BooleanField(default=True)),
                ('auto_retrain_after_manual_entry', models.BooleanField(default=True)),
                ('auto_retrain_after_bulk_upload', models.BooleanField(default=True)),
                ('auto_retrain_after_doctor_review', models.BooleanField(default=False)),
                ('min_new_records_for_retrain', models.PositiveIntegerField(default=10)),
                ('retrain_cooldown_minutes', models.PositiveIntegerField(default=15)),
                ('pending_training_records', models.PositiveIntegerField(default=0)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('last_training_status', models.CharField(default='idle', max_length=20)),
                ('last_training_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'verbose_name_plural': 'AI Model Configuration',
            },
        ),
        migrations.CreateModel(
            name='TrainingDatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('source_label', models.CharField(blank=True, max_length=150)),
                ('dataset_file', models.FileField(upload_to='training_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('partial', 'Processed with warnings'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('auto_retrain_requested', models.BooleanField(default=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('summary_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_dataset_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('source_type', models.CharField(choices=[('admin_manual', 'Admin manual entry'), ('admin_bulk_upload', 'Admin bulk upload')], default='admin_manual', max_length=40)),
                ('input_text', models.TextField()),
                ('ai_context', models.TextField(blank=True)),
                ('target_condition', models.CharField(max_length=120)),
                ('target_specialization', models.CharField(blank=True, max_length=150)),
                ('target_treatment', models.TextField()),
                ('feature_snapshot', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.PositiveSmallIntegerField(default=70)),
                ('is_approved', models.BooleanField(default=True)),
                ('review_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_knowledge_entries', to=settings.AUTH_USER_MODEL)),
                ('uploaded_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='medical_app.trainingdatasetupload')),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['source_type', 'is_approved', '-updated_at'], name='knowledge_source_approved_idx')],
            },
        ),
    ]
