# Generated by Django 6.0.3 on 2026-03-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0009_aimodelconfiguration_trainingdatasetupload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdatasetupload',
            name='error_report_file',
            field=models.FileField(blank=True, null=True, upload_to='training_upload_errors/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_console_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AITrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, max_length=40)),
                ('run_reason', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('pending_record_snapshot', models.PositiveIntegerField(default=0)),
                ('classifier_record_count', models.PositiveIntegerField(default=0)),
                ('qa_corpus_count', models.PositiveIntegerField(default=0)),
                ('classifier_accuracy', models.FloatField(blank=True, null=True)),
                ('classifier_macro_f1', models.FloatField(blank=True, null=True)),
                ('classifier_weighted_f1', models.FloatField(blank=True, null=True)),
                ('qa_hit_rate_at_1', models.FloatField(blank=True, null=True)),
                ('qa_average_score', models.FloatField(blank=True, null=True)),
                ('is_active_version', models.BooleanField(default=False)),
                ('log_output', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['status', '-started_at'], name='training_run_status_idx'), models.Index(fields=['is_active_version', '-started_at'], name='training_run_active_idx')],
            },
        ),
    ]
