# Generated by Django 6.0.3 on 2026-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_app", "0010_trainingdatasetupload_error_report_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitrainingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
